version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: microservices_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: microservices_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"

  eureka-service:
    build:
      context: .
      dockerfile: eureka-service/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - mysql
      - postgres

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - eureka-service

  course-service:
    build:
      context: .
      dockerfile: course-service/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - eureka-service

  exam-service:
    build:
      context: .
      dockerfile: exam-service/Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - user-service
      - course-service
      - eureka-service

  answer-service:
    build:
      context: .
      dockerfile: answer-service/Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      - user-service
      - exam-service
      - eureka-service

  zuul-service:
    build:
      context: .
      dockerfile: zuul-service/Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - user-service
      - course-service
      - exam-service
      - answer-service
      - eureka-service

  # Optional if you're using api-gateway-service instead
  api-gateway-service:
    build:
      context: .
      dockerfile: api-gateway-service/Dockerfile
    ports:
      - "8086:8080"
    depends_on:
      - user-service
      - course-service
      - exam-service
      - answer-service
      - eureka-service

